---
- name: test1
  gather_facts: false
  hosts: web_b
  vars:
    ansible_ssh_user: user
  become: yes

  pre_tasks:
    - name: Validating the ssh port is open and
      wait_for:
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
        port: 22
        delay: 5
        timeout: 300
        state: started
        search_regex: OpenSSH

  tasks:
    - name: create test file
      copy:
        dest: /tmp/test
        content: "success"

    - name: install mysql 
      apt: 
        name: mysql-server
        cache_valid_time: 3600
        state: present
        update_cache: yes

    - name: ensure mysql is enabled to run on startup 
      service: 
        name: mysql 
        state: started 
        enabled: true

  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted      
